### ISSUE TITLE
Página de meus cursos

### ISSUE THREAD

**Issue by Atzingen** [Atzingen/corretorIA#5]
Criar uma página onde os cursos do aluno ficam disponíveis e separados por: Cursando, Finalizados e Aguardando início.

Atualmente isso é mostrado na página de início, mas o idela é deixar a home com anúncios de cursos novos, login e inscrição.

**Comment by arquejadalucy** [comment]
![image](https://user-images.githubusercontent.com/82039346/197915080-fb6b3a49-308c-4d58-9b95-9aa74a206fbe.png)
![image](https://user-images.githubusercontent.com/82039346/197915121-1497c677-909b-451d-8950-ad07f55dbcc1.png)
![image](https://user-images.githubusercontent.com/82039346/197915166-0aa0d87e-77a0-47e6-af73-8bb8b2ec7f97.png)
